- name: Netlify Deploy
  uses: jsmrcaga/action-netlify-deploy@v1.6.0
  with:
    NETLIFY_AUTH_TOKEN: KipO_oLTMvazFK1D3WzZZizMbndzM20CnA7mDNxYasY
    NETLIFY_SITE_ID: c2864d17-015e-4f1e-8fd6-8ba126b10e1c
    build_directory: dist
